name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: 0.7.13
          enable-cache: "true"
          cache-suffix:  ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: uv sync --frozen
        shell: bash

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run tests with coverage
        run: |
          # Run pytest with coverage
          uv run pytest --cov=. --cov-report=xml
          # Generate batch
          uv run coverage-badge -o coverage.svg
